const { DataTypes } = require('sequelize');
const sequelize = require('../db');

const Booking = sequelize.define('Booking', {
    name: { type: DataTypes.STRING, allowNull: false },
    email: { type: DataTypes.STRING, allowNull: false },
    phone: { type: DataTypes.STRING, allowNull: false },
    alternativePhone: { type: DataTypes.STRING },
    whatsappNumber: { type: DataTypes.STRING },
    onSiteContactPerson: { type: DataTypes.STRING },
    contactPhone: { type: DataTypes.STRING },
    relationshipToHost: { type: DataTypes.STRING },
    eventType: { type: DataTypes.ENUM('Birthday Party', 'Wedding/Reception', 'Corporate Event', 'Anniversary', 'Housewarming', 'Festival Celebration', 'Bachelor/Bachelorette Party', 'Cocktail Party', 'Other'), allowNull: false },
    eventTypeOther: { type: DataTypes.STRING },
    eventDate: { type: DataTypes.DATEONLY, allowNull: false },
    eventStartTime: { type: DataTypes.TIME, allowNull: false },
    eventEndTime: { type: DataTypes.TIME, allowNull: false },
    barServiceDuration: { type: DataTypes.INTEGER },
    totalGuests: { type: DataTypes.INTEGER },
    adultGuests: { type: DataTypes.INTEGER },
    minorGuests: { type: DataTypes.INTEGER },
    peakBarUsageStartTime: { type: DataTypes.TIME },
    peakBarUsageEndTime: { type: DataTypes.TIME },
    eventTheme: { type: DataTypes.STRING },
    preferredAtmosphere: { type: DataTypes.JSONB },
    fullAddress: { type: DataTypes.STRING },
    city: { type: DataTypes.STRING },
    state: { type: DataTypes.STRING },
    pinCode: { type: DataTypes.STRING },
    landmark: { type: DataTypes.STRING },
    venueType: { type: DataTypes.ENUM('Private Residence (Home)', 'Banquet Hall', 'Hotel', 'Outdoor Venue/Garden', 'Rooftop', 'Farmhouse', 'Club/Resort', 'Office Space', 'Other') },
    venueTypeOther: { type: DataTypes.STRING },
    parkingAvailable: { type: DataTypes.BOOLEAN },
    parkingType: { type: DataTypes.ENUM('2 wheeler', '4 wheeler') },
    elevatorAccess: { type: DataTypes.BOOLEAN },
    floorNumber: { type: DataTypes.INTEGER },
    specialEntryInstructions: { type: DataTypes.STRING },
    preferredBarLocation: { type: DataTypes.JSONB },
    preferredBarLocationOther: { type: DataTypes.STRING },
    barTableAvailable: { type: DataTypes.BOOLEAN },
    arrangeTemporarySetup: { type: DataTypes.BOOLEAN },
    powerOutletAvailable: { type: DataTypes.BOOLEAN },
    waterSourceAvailable: { type: DataTypes.BOOLEAN },
    distanceToWaterPoint: { type: DataTypes.INTEGER },
    sinkAvailable: { type: DataTypes.BOOLEAN },
    wineGlassesAvailable: { type: DataTypes.BOOLEAN },
    wineGlassesQuantity: { type: DataTypes.STRING },
    beerMugsAvailable: { type: DataTypes.BOOLEAN },
    beerMugsQuantity: { type: DataTypes.STRING },
    whiskeyGlassesAvailable: { type: DataTypes.BOOLEAN },
    whiskeyGlassesQuantity: { type: DataTypes.STRING },
    shotGlassesAvailable: { type: DataTypes.BOOLEAN },
    champagneFlutesAvailable: { type: DataTypes.BOOLEAN },
    champagneFlutesQuantity: { type: DataTypes.STRING },
    cocktailGlassesAvailable: { type: DataTypes.BOOLEAN },
    cocktailGlassesQuantity: { type: DataTypes.STRING },
    highballGlassesAvailable: { type: DataTypes.BOOLEAN },
    highballGlassesQuantity: { type: DataTypes.STRING },
    margaritaGlassesAvailable: { type: DataTypes.BOOLEAN },
    margaritaGlassesQuantity: { type: DataTypes.STRING },
    disposableOptionsAvailable: { type: DataTypes.BOOLEAN },
    cocktailShakerAvailable: { type: DataTypes.BOOLEAN },
    barSpoonsAvailable: { type: DataTypes.BOOLEAN },
    muddlerAvailable: { type: DataTypes.BOOLEAN },
    jiggerAvailable: { type: DataTypes.BOOLEAN },
    strainerAvailable: { type: DataTypes.BOOLEAN },
    bottleOpenerAvailable: { type: DataTypes.BOOLEAN },
    corkscrewAvailable: { type: DataTypes.BOOLEAN },
    cuttingBoardAvailable: { type: DataTypes.BOOLEAN },
    sharpKnifeAvailable: { type: DataTypes.BOOLEAN },
    refrigeratorAccess: { type: DataTypes.BOOLEAN },
    freezerAccess: { type: DataTypes.BOOLEAN },
    iceBucketsAvailable: { type: DataTypes.BOOLEAN },
    iceBucketsQuantity: { type: DataTypes.STRING },
    coolersAvailable: { type: DataTypes.BOOLEAN },
    coolersQuantity: { type: DataTypes.STRING },
    servingTraysAvailable: { type: DataTypes.BOOLEAN },
    servingTraysQuantity: { type: DataTypes.STRING },
    largeTraysAvailable: { type: DataTypes.BOOLEAN },
    smallCocktailTraysAvailable: { type: DataTypes.BOOLEAN },
    antiSlipTraysAvailable: { type: DataTypes.BOOLEAN },
    cocktailNapkinsAvailable: { type: DataTypes.BOOLEAN },
    coastersAvailable: { type: DataTypes.BOOLEAN },
    iceTongsAvailable: { type: DataTypes.BOOLEAN },
    servingSpoonsAvailable: { type: DataTypes.BOOLEAN },
    freshFruitsAvailable: { type: DataTypes.BOOLEAN },
    lemonsAvailable: { type: DataTypes.BOOLEAN },
    lemonsQuantity: { type: DataTypes.STRING },
    limesAvailable: { type: DataTypes.BOOLEAN },
    orangesAvailable: { type: DataTypes.BOOLEAN },
    orangesQuantity: { type: DataTypes.STRING },
    otherFruitsAvailable: { type: DataTypes.BOOLEAN },
    otherFruitsSpecify: { type: DataTypes.STRING },
    cherriesAvailable: { type: DataTypes.BOOLEAN },
    mintLeavesAvailable: { type: DataTypes.BOOLEAN },
    cucumberAvailable: { type: DataTypes.BOOLEAN },
    olivesAvailable: { type: DataTypes.BOOLEAN },
    softDrinksAvailable: { type: DataTypes.BOOLEAN },
    cokePepsiAvailable: { type: DataTypes.BOOLEAN },
    sprite7upAvailable: { type: DataTypes.BOOLEAN },
    sprite7upQuantity: { type: DataTypes.STRING },
    otherSodasAvailable: { type: DataTypes.BOOLEAN },
    otherSodasSpecify: { type: DataTypes.STRING },
    tonicWaterAvailable: { type: DataTypes.BOOLEAN },
    tonicWaterQuantity: { type: DataTypes.STRING },
    sodaWaterAvailable: { type: DataTypes.BOOLEAN },
    sodaWaterQuantity: { type: DataTypes.STRING },
    gingerAleAvailable: { type: DataTypes.BOOLEAN },
    gingerAleQuantity: { type: DataTypes.STRING },
    freshJuicesAvailable: { type: DataTypes.BOOLEAN },
    freshJuicesSpecify: { type: DataTypes.STRING },
    regularWaterAvailable: { type: DataTypes.BOOLEAN },
    regularWaterQuantity: { type: DataTypes.STRING },
    sparklingWaterAvailable: { type: DataTypes.BOOLEAN },
    sparklingWaterQuantity: { type: DataTypes.STRING },
    specificRequirementsAvailable: { type: DataTypes.BOOLEAN },
    specificRequirementsSpecify: { type: DataTypes.STRING },
    signatureCocktailDesired: { type: DataTypes.BOOLEAN },
    preferredCocktails: { type: DataTypes.JSONB },
    customCocktailRequest: { type: DataTypes.STRING },
    sugarFreeOptionsRequired: { type: DataTypes.BOOLEAN },
    lowAlcoholMocktailOptions: { type: DataTypes.BOOLEAN },
    religiousCulturalRestrictions: { type: DataTypes.STRING },
    allergyConsiderations: { type: DataTypes.STRING },
    preferredAttire: { type: DataTypes.JSONB },
    themedAttireSpecify: { type: DataTypes.STRING },
    languagePreferences: { type: DataTypes.JSONB },
    regionalLanguageSpecify: { type: DataTypes.STRING },
}, { 
    timestamps: true,
    tableName: 'bookings'
});

module.exports = Booking;